DROP TABLE IF EXISTS vinyl;

CREATE TABLE vinyl (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    artist TEXT NOT NULL,
    album TEXT NOT NULL,
    rel_year INTEGER NOT NULL,
    label TEXT NOT NULL

);